version: '2'

services:

# ### Golang Container #########################################

    email-service:
        build:
            context: .
        ports:
            - "8080:8080"
            # - "443:443"
