version: '2'

services:

# ### Golang Container for Development #########################################

    email-service:
        build:
            context: .
        ports:
            - "8080:8080"